---
Name: dataobject-searcher
After:
  - 'dataobject-manager/*'
---

nglasl\extensible\ExtensibleSearchPage:
  custom_search_engines:
    HudhaifaS\DOM\Search\DOMSearchEngine: 'DOM'

nglasl\extensible\ExtensibleSearchPageController:
  extensions:
    - 'HudhaifaS\DOM\Search\DOMSearchFormExtention'

PageController:
  extensions:
    - 'nglasl\extensible\ExtensibleSearchExtension'
    - 'HudhaifaS\DOM\Search\DOMSearchEngineExtension'

SilverStripe\ORM\DataObject:
  extensions:
    - 'HudhaifaS\DOM\Search\DOMFluentExtension'