---
Name: dataobject-searcher
After:
  - 'dataobject-manager/*'
---

DataObjectPageController:
  extensions:
    - DefaultSearchFormExtension

DefaultSearchPageController:
  extensions:
    - DefaultSearchFormExtension