---
Name: dataobject-searcher
After:
  - 'dataobject-manager/*'
---

DataObjectPage_Controller:
  extensions:
    - DefaultSearchFormExtension

DefaultSearchPage_Controller:
  extensions:
    - DefaultSearchFormExtension